(defstruct sit av df hp dammod save)

(defun d (n) (1+ (random n)))

(defun deathp (sit attack damdie)
  (let* ((mult (if (= attack (sit-av sit)) 2 1))
	 (crittable (if (and (= mult 2)
			     (= damdie 1))
			(d 20)
			0))
	 (damage (if (< (sit-df sit) attack (1+ (sit-av sit)))
		     (let* ((raw (+ damdie (sit-dammod sit)))
			    (regular (if (plusp raw)
					 (* raw mult)
					 mult)))
		       (if (= crittable 14)
			   (+ regular (d 6))
			   regular))
		     0)))
    (or (= crittable 20)
	(and (<= (- (sit-hp sit) damage) -2)        
	     (or (> (d 20) (sit-save sit))
		 (<= (- (+ (sit-hp sit) (d 6))
			damage)
		     -2))
	     (> (d 20) (sit-save sit))))))

(defun death-risk (sit &key (times 10000000) (damsides 6))
  (float (/ (loop repeat times sum (if (deathp sit (d 20) (d damsides))
				       1 
				       0)) 
	    times)))
